//! Application → STM32 system-memory (ROM) bootloader handoff.
//!
//! The ROM bootloader is normally entered by strapping BOOT0 at reset, but it
//! can also be reached by a software jump to the system-memory reset vector.
//! On this board BOOT0 is shared with `PB8` (I²C1_SCL) and pulled up to a
//! switched rail generated by the TPS26750, so the pin route is unreliable; a
//! software jump needs no option-byte change, no strapping and no SWD probe.
//!
//! The jump is deliberately **not** performed from the call site. Instead the
//! caller records a request in `.uninit` RAM and issues a system reset; the
//! request is consumed at the very top of `main`, before Embassy starts the
//! executor or touches any peripheral, so the bootloader is entered from a
//! pristine machine state. `SCB::sys_reset()` also returns the clock tree to
//! its reset default, which is exactly what the ROM loader expects.
//!
//! See AN2606 (STM32 microcontroller system memory boot mode) for the entry
//! address and the USART it listens on.

use core::sync::atomic::{AtomicU32, Ordering};

/// STM32G47xxx system-memory (bootloader) base address, per AN2606.
pub const SYSTEM_MEMORY_BASE: usize = 0x1FFF_0000;

/// Request marker. A second word holds its complement, so a cold-boot SRAM
/// collision has to match 64 bits rather than 32.
const MAGIC: u32 = 0xB007_10AD;

// cortex-m-rt's `link.x` places `.uninit` in NOLOAD RAM: the startup code does
// not zero it and it does not overlap `.data`/`.bss`. These words therefore
// survive a system reset, and are uninitialised (arbitrary) after power-on.
#[link_section = ".uninit"]
static REQUEST_MAGIC: AtomicU32 = AtomicU32::new(0);
#[link_section = ".uninit"]
static REQUEST_INVERSE: AtomicU32 = AtomicU32::new(0);

/// Record a request to enter the ROM bootloader on the next boot, then reset.
///
/// Diverges: the caller never returns.
pub fn request_on_next_boot() -> ! {
    REQUEST_MAGIC.store(MAGIC, Ordering::SeqCst);
    REQUEST_INVERSE.store(!MAGIC, Ordering::SeqCst);
    cortex_m::peripheral::SCB::sys_reset()
}

/// Consume a pending request, returning `(was_valid, magic_raw, inverse_raw,
/// valid_count_since_power_on)` so callers can diagnose a handoff that did not
/// survive the reset. The counter is itself in `.uninit`, so it survives the
/// resets whose side effects it counts.
pub fn take_request_diag() -> (bool, u32, u32, u32) {
    let magic = REQUEST_MAGIC.swap(0, Ordering::SeqCst);
    let inverse = REQUEST_INVERSE.swap(0, Ordering::SeqCst);
    let valid = magic == MAGIC && inverse == !MAGIC;
    if valid {
        JUMP_COUNT.fetch_add(1, Ordering::SeqCst);
    }
    (valid, magic, inverse, JUMP_COUNT.load(Ordering::SeqCst))
}

/// Diagnostic: how many times a valid handoff request was consumed since
/// power-on. Distinguishes "the marker never survived" (0) from "it was
/// consumed and the jump path then failed" (>0).
#[link_section = ".uninit"]
static JUMP_COUNT: AtomicU32 = AtomicU32::new(0);

/// Consume a pending request.
///
/// Call as the first statement in `main`. Returns `true` exactly once per
/// [`request_on_next_boot`] call, so the handoff cannot loop on a held trigger.
pub fn take_request() -> bool {
    take_request_diag().0
}

/// Branch to the ROM bootloader at [`SYSTEM_MEMORY_BASE`]. Diverges.
///
/// After the branch the only way back is a reset or the bootloader's own `Go`
/// command, so this is only called once the output has been parked.
pub fn jump_to_system_bootloader() -> ! {
    // The ROM bootloader is written to run straight out of reset, so give it
    // the core state it would have had then. Leaving our own interrupt state
    // behind is what makes the G4 loader start and then fall straight back into
    // the application: it masks nothing, expects SysTick off, no NVIC line
    // enabled or pending, and interrupts unmasked (PRIMASK clear) -- the
    // opposite of the usual "disable interrupts before jumping" folklore.
    cortex_m::interrupt::disable();
    // SAFETY: NVIC and SysTick are core peripherals at fixed addresses.
    unsafe {
        const NVIC_ICER: *mut u32 = 0xE000_E180 as *mut u32;
        const NVIC_ICPR: *mut u32 = 0xE000_E280 as *mut u32;
        const SYST_CSR: *mut u32 = 0xE000_E010 as *mut u32;
        for i in 0..8 {
            core::ptr::write_volatile(NVIC_ICER.add(i), 0xFFFF_FFFF);
            core::ptr::write_volatile(NVIC_ICPR.add(i), 0xFFFF_FFFF);
        }
        core::ptr::write_volatile(SYST_CSR, 0);
    }
    // Interrupts back on, exactly as after reset, now that nothing can fire.
    // SAFETY: every NVIC line was just disabled and its pending bit cleared, so
    // no handler of ours can run between here and the branch below.
    unsafe { cortex_m::interrupt::enable() };

    // Point VTOR at the bootloader before handing over. The ROM reset handler
    // establishes its own state, but this keeps a straggler exception from
    // landing on our (now stale) vector table.
    const VTOR: *mut u32 = 0xE000_ED08 as *mut u32;
    // SAFETY: VTOR is a core register always mapped at this address.
    unsafe { core::ptr::write_volatile(VTOR, SYSTEM_MEMORY_BASE as u32) };

    // SAFETY: system memory holds a valid vector table — initial MSP at +0 and
    // reset vector at +4 — on every STM32G47xxx. `bootload` reads both, switches
    // to the bootloader's stack, and branches to its reset handler in a single
    // asm block. Doing that around an ordinary function call is UB (`msp::write`
    // is deprecated for exactly this reason), so use the library's sequence.
    unsafe { cortex_m::asm::bootload(SYSTEM_MEMORY_BASE as *const u32) }
}
