use std::{env, fs, path::PathBuf};

fn main() {
    println!("cargo:rustc-link-arg=-Tlink.x");
    println!("cargo:rerun-if-changed=src/drivers/config_TPS26750_F8091159_fullFlash.c");

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let source_path = manifest_dir.join("src/drivers/config_TPS26750_F8091159_fullFlash.c");
    let source = fs::read_to_string(&source_path).unwrap();
    let bytes = parse_c_byte_array(&source);

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let out_path = out_dir.join("tps26750_full_flash.rs");
    let mut rust = String::new();
    rust.push_str("// Generated by build.rs from config_TPS26750_F8091159_fullFlash.c\n");
    rust.push_str(&format!(
        "pub const TPS26750_FULL_FLASH_LEN: usize = {};\n",
        bytes.len()
    ));
    rust.push_str(&format!(
        "pub static TPS26750_FULL_FLASH_BYTES: [u8; {}] = [\n",
        bytes.len()
    ));
    for chunk in bytes.chunks(16) {
        rust.push_str("    ");
        for byte in chunk {
            rust.push_str(&format!("0x{byte:02x}, "));
        }
        rust.push('\n');
    }
    rust.push_str("];\n");
    fs::write(out_path, rust).unwrap();
}

fn parse_c_byte_array(source: &str) -> Vec<u8> {
    let start = source
        .find('{')
        .expect("TPS26750 full-flash C array is missing '{'");
    let end = source[start..]
        .find("};")
        .map(|idx| start + idx)
        .expect("TPS26750 full-flash C array is missing '};'");

    source[start + 1..end]
        .split(',')
        .filter_map(|token| {
            let token = token.trim();
            if token.is_empty() {
                None
            } else {
                let hex = token
                    .strip_prefix("0x")
                    .expect("TPS26750 full-flash array contains a non-hex byte");
                Some(u8::from_str_radix(hex, 16).unwrap())
            }
        })
        .collect()
}
